import { NgModule } from '@angular/core';
import {
  GridModule,
  PageService,
  SortService,
  FilterService,
  ExcelExportService,
  EditService,
  ResizeService,
  ToolbarService,
  ColumnChooserService,
  AggregateService,
  ColumnMenuService,
  DetailRowService,
  SelectionService,
  PagerModule,
  GroupService,
  GridAllModule,
} from '@syncfusion/ej2-angular-grids';
import {
  SwitchModule,
  CheckBoxModule,
  RadioButtonModule,
  ButtonModule,
} from '@syncfusion/ej2-angular-buttons';
import { DiagramModule } from '@syncfusion/ej2-angular-diagrams';
import {
  TreeGridAllModule,
  TreeGridModule,
  EditService as TreeGridEditService,
  ExcelExportService as TreeExcelExportService,
} from '@syncfusion/ej2-angular-treegrid';
import { TooltipModule, DialogModule } from '@syncfusion/ej2-angular-popups';
import {
  DatePickerModule,
  DateRangePickerModule,
  DateTimePickerModule,
} from '@syncfusion/ej2-angular-calendars';
import {
  TextBoxModule,
  ColorPickerModule,
} from '@syncfusion/ej2-angular-inputs';
import {
  DropDownListModule,
  MultiSelectAllModule,
  AutoCompleteModule,
} from '@syncfusion/ej2-angular-dropdowns';
import {
  PivotViewAllModule,
  PivotFieldListAllModule,
} from '@syncfusion/ej2-angular-pivotview';
import {
  ChartAllModule,
  AccumulationChartAllModule,
  RangeNavigatorAllModule,
  AccumulationChartModule,
  PieSeriesService,
  AccumulationLegendService,
  AccumulationTooltipService,
  AccumulationAnnotationService,
  AccumulationDataLabelService,
} from '@syncfusion/ej2-angular-charts';
import { DashboardLayoutModule } from '@syncfusion/ej2-angular-layouts';
import {
  CarouselAllModule,
  ToolbarModule,
} from '@syncfusion/ej2-angular-navigations';
import {
  PdfViewerModule,
  LinkAnnotationService,
  BookmarkViewService,
  MagnificationService,
  ThumbnailViewService,
  ToolbarService as PbfToolbarService,
  NavigationService,
  TextSearchService,
  TextSelectionService,
  PrintService,
} from '@syncfusion/ej2-angular-pdfviewer';
import { DropDownButtonModule } from '@syncfusion/ej2-angular-splitbuttons';
import {
  RichTextEditorAllModule,
  HtmlEditorService,
  ToolbarService as RichEditorToolbarService,
} from '@syncfusion/ej2-angular-richtexteditor';
import { ListBoxModule } from '@syncfusion/ej2-angular-dropdowns';
import {
  UploaderModule,
  NumericTextBoxModule,
} from '@syncfusion/ej2-angular-inputs';

@NgModule({
  imports: [
    SwitchModule,
    GridModule,
    CheckBoxModule,
    DiagramModule,
    TooltipModule,
    TreeGridAllModule,
    RadioButtonModule,
    DatePickerModule,
    DateRangePickerModule,
    DateTimePickerModule,
    TextBoxModule,
    ButtonModule,
    DropDownListModule,
    MultiSelectAllModule,
    PagerModule,
    PivotViewAllModule,
    PivotFieldListAllModule,
    ChartAllModule,
    AccumulationChartAllModule,
    RangeNavigatorAllModule,
    DashboardLayoutModule,
    CarouselAllModule,
    ToolbarModule,
    TreeGridModule,
    PdfViewerModule,
    AccumulationChartModule,
    DropDownButtonModule,
    AutoCompleteModule,
    ColorPickerModule,
    GridAllModule,
    RichTextEditorAllModule,
    DialogModule,
    ListBoxModule,
    NumericTextBoxModule,
    UploaderModule,
  ],
  exports: [
    SwitchModule,
    GridModule,
    CheckBoxModule,
    DiagramModule,
    TooltipModule,
    TreeGridAllModule,
    DatePickerModule,
    DateRangePickerModule,
    DateTimePickerModule,
    RadioButtonModule,
    TextBoxModule,
    ButtonModule,
    DropDownListModule,
    MultiSelectAllModule,
    PagerModule,
    PivotViewAllModule,
    PivotFieldListAllModule,
    ChartAllModule,
    AccumulationChartAllModule,
    RangeNavigatorAllModule,
    DashboardLayoutModule,
    CarouselAllModule,
    ToolbarModule,
    TreeGridModule,
    PdfViewerModule,
    AccumulationChartModule,
    DropDownButtonModule,
    AutoCompleteModule,
    ColorPickerModule,
    GridAllModule,
    RichTextEditorAllModule,
    DialogModule,
    ListBoxModule,
    NumericTextBoxModule,
    UploaderModule,
  ],
  providers: [
    PageService,
    SortService,
    FilterService,
    ExcelExportService,
    EditService,
    ResizeService,
    ToolbarService,
    ColumnChooserService,
    AggregateService,
    DetailRowService,
    SelectionService,
    TreeGridEditService,
    TreeExcelExportService,
    PbfToolbarService,
    LinkAnnotationService,
    BookmarkViewService,
    MagnificationService,
    ThumbnailViewService,
    NavigationService,
    TextSearchService,
    TextSelectionService,
    PrintService,
    PieSeriesService,
    AccumulationLegendService,
    AccumulationTooltipService,
    AccumulationAnnotationService,
    AccumulationDataLabelService,
    GroupService,
    ColumnMenuService,
    HtmlEditorService,
    RichEditorToolbarService,
  ],
})
export class SharedSyncfusionModule {}
